spark-submit --class bgc.transformation bgc-etl-v7.jar



									  
						 
									  

										
					   
  
									 
														 
															
															   
																
														  
															
														  
																 
														
  
  
					   
								 
   
											 
												   
												 
	
																  
																		
								   
									   
	
						  
	
									  
	
																																													  
																															 
	
										  
																																										 
	
																									 
																									 
																				  
 
   
																			 
																																				   
																		  
   
						
																											
   
																									   
   
																																							
   
												
   
																					   
   
																										 
   
																																				   
   
																				   
																						
																				  
																							  
																														
				
															 
  
																						  
		
																				  
																						 
																	  
																 
																			 
																	
																
									  
												 
   
							   
													  
								  
		 
	
										  
	
						 
							 
	
														
																	  
																	
	
							   

																								 
																	 
			 
	 
 